GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvb2giLCJpZCI6IjY2MzNiYTdkNTdhNGNkNGI1YjRjZWU3YSIsImlhdCI6MTcxNDY2ODcxOSwiZXhwIjoxNzE0NjcyMzE5fQ.tWzRsXivXSfxANBUEABmwc_YUWMCscOOq4CdJZoBjvs
